name: shell_build

on: [pull_request]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: Download build script
    - run: wget https://raw.githubusercontent.com/stewart-lab/fast_km/master/actions/build_workflow.sh
    
    - name: Run build script
    - run: chmod +x ./build_workflow.sh
    - run: ./build_workflow.sh
